name: DB Objects Registry Update

on:
  push:
    branches:
      - '**' # Runs on every branch push
  pull_request:
    branches: [ ]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: read

jobs:
  db_objects_registry:
    name: DB Objects Registry Update
    timeout-minutes: 20
    runs-on: ubuntu-latest
    # Deploy to the github-pages environment
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout test repository
        id: checkout_coredatabase_repo
        uses: actions/checkout@v4
        with:
          path: test
          fetch-depth: 0

      # - name: Upload pages artifact
      #   id: upload_pages_artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: 'test/gh_pages'

      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
